[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*.dll"
  [headers.values]
    Content-Type = "application/octet-stream"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200